<?php
	require_once "../akses.php";
	require_once "../function/encrypt-decrypt-file.php";
	$id_user = decrypt($_SESSION['tiket_id'], $key_global);

	// Penghubung Library
	require_once '../assets/vendor/autoload.php';
	// Library Tangal
	use Carbon\Carbon;
	$datetime_now = Carbon::now();

	// Library Debugging
	use Whoops\Run;
	use Whoops\Handler\PrettyPageHandler;
	// Inisialisasi Whoops
	// Atur status aktif/non-aktif Whoops
	$whoops_enabled = false; // Ubah menjadi false untuk menonaktifkan

	if ($whoops_enabled) {
		$whoops = new \Whoops\Run();
		$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler());
		$whoops->register();
	}
	// Library sanitasi input data
	require_once "../function/sanitasi_input.php";
	$sanitasi_post = sanitizeInput($_POST);
	$sanitasi_get = sanitizeInput($_GET);

	// Simpan
	if (isset($sanitasi_post["simpan-kat-produk"])) {
		$id_kat_produk = $sanitasi_post['id_kat_produk'];
		$nama_kategori = $sanitasi_post['nama_kat_produk'];
		$merk = $sanitasi_post['merk'];
		$nie = $sanitasi_post['nie'];
		$tgl_terbit = $sanitasi_post['tgl_terbit'];
		$expired_date = $sanitasi_post['expired_date'];

		$nama_kategori_replace = str_replace(' ', '_', $nama_kategori);  // Mengganti semua spasi dengan underscore

		$cek_kat = mysqli_query($connect, "SELECT nama_kategori FROM tb_kat_produk WHERE nama_kategori = '$nama_kategori' AND id_merk = '$merk'");
		$path = "../files/";
		if (!file_exists($path)) {
			// Folder belum ada, buat folder baru
			mkdir($path, 0777, true);
		}

		if ($cek_kat->num_rows > 0) {
			$_SESSION['info'] = 'Data sudah ada';
			header("Location:../kategori-produk.php");
		} else {
			// Inisialisasi variabel sebelum digunakan
			$file_path = ''; 
			$pdf_path = '';
			$file_path_db = '';
			// Jika file diunggah
            if (!empty($_FILES["fileku"]["tmp_name"])) {
				// Mendapatkan informasi file
				$allowed_images = ['image/png', 'image/jpg', 'image/jpeg'];
				$allowed_pdfs = ['application/pdf'];
				$file_type = $_FILES['fileku']['type'];
                
				$upload_dir = __DIR__ . '/../files/';
				
				if (!is_dir($upload_dir)) {
					mkdir($upload_dir, 0777, true);
				}

				$file_name = basename($_FILES['fileku']['name']);
				$new_file_name = $nama_kategori_replace . '_' .  time() . uniqid() . '.pdf';
				$file_path = $upload_dir . $new_file_name;
				// Untuk di simpan di table
				$file_path_db = 'files/' . $new_file_name;
				// Jika file adalah PDF, langsung simpan dan redirect
				if (in_array($file_type, $allowed_pdfs)) {
					
					// Pindahkan file PDF ke folder tujuan sebelum enkripsi
					if (!move_uploaded_file($_FILES['fileku']['tmp_name'], $file_path)) {
						throw new Exception("Gagal memindahkan file PDF ke lokasi tujuan: " . $file_path);
					}

					// Debugging: Pastikan file ada sebelum enkripsi
					if (!file_exists($file_path)) {
						throw new Exception("File tidak ditemukan sebelum enkripsi: " . $file_path);
					}

					echo "PDF Moved Successfully - Path: " . $file_path . "<br>";

					// Enkripsi file PDF sebelum menyimpannya
					$encryptedFileContent = encryptFile($file_path, $fileKey);
					if (!$encryptedFileContent) {
						throw new Exception("Enkripsi gagal: File terenkripsi kosong.");
					}

					// Simpan file yang telah dienkripsi
					if (file_put_contents($file_path, $encryptedFileContent) === false) {
						throw new Exception('Gagal menyimpan file di server.');
					}

					echo "Encryption Success - File Saved!<br>";
				} else if (in_array($file_type, $allowed_images)){
					// Konversi gambar ke PDF langsung dari tmp_name
					$pdf = new TCPDF();
					$pdf->SetCreator(PDF_CREATOR);
					$pdf->SetAuthor('Generated by PHP');
					$pdf->SetTitle('Converted Image to PDF');
					$pdf->SetMargins(10, 10, 10);
					$pdf->AddPage();

					// Tambahkan gambar ke dalam PDF langsung dari $_FILES['fileku']['tmp_name']
					$pdf->Image($_FILES['fileku']['tmp_name'], 10, 10, 190, '', '', '', '', false, 300);

					// Simpan file PDF
					$pdf_name = $new_file_name;
					$pdf_path = $upload_dir . $pdf_name;
					$pdf->Output($pdf_path, 'F');

					// Enkripsi file PDF sebelum menyimpannya
					$encryptedFileContent = encryptFile($pdf_path, $fileKey);

					// Menyimpan file yang telah dienkripsi
					if (file_put_contents($pdf_path, $encryptedFileContent) === false) {
						throw new Exception('Gagal menyimpan file di server.');
					}
				}
            }
			
			try {
				// Siapkan query menggunakan prepared statement
				$stmt = $connect->prepare("INSERT INTO tb_kat_produk
											(id_kat_produk, nama_kategori, id_merk, no_izin_edar, tgl_terbit, berlaku_sampai, file_nie, created_by) 
											VALUES 
											(?, ?, ?, ?, ?, ?, ?, ?)");
				// Bind parameter
				$stmt->bind_param("ssssssss", $id_kat_produk, $nama_kategori, $merk, $nie, $tgl_terbit, $expired_date, $file_path_db, $id_user);
			
				// Eksekusi query
				if ($stmt->execute()) {
					$_SESSION['info'] = 'Disimpan';
					header("Location: ../kategori-produk.php");
					exit;
				}
			} catch (mysqli_sql_exception $e) {
				if (!empty($file_path) && file_exists($file_path)) { // Cek sebelum unlink
					unlink($file_path);
				}
				echo "Terjadi kesalahan: " . $e->getMessage();
				// Tangani error jika terjadi kesalahan pada query
				$_SESSION['info'] = 'Data Gagal Disimpan';
				// header("Location: ../kategori-produk.php");
				exit;
			} finally {
				// Tutup statement jika sudah dibuat
				if (isset($stmt)) {
					$stmt->close();
				}
			}
		}

		//Edit
	} elseif (isset($sanitasi_post["edit-kat-produk"])) {
		$id_kat_produk = decrypt($sanitasi_post['id_kat_produk'], $key_global);
		$nama_kategori = $sanitasi_post['nama_kat_produk'];
		$merk = $sanitasi_post['merk'];
		$nie = $sanitasi_post['no_izin_edar'];
		$tgl_terbit = $sanitasi_post['tgl_terbit'];
		$expired_date = $sanitasi_post['exp_date'];

		$upload_dir = __DIR__ . '/../files/';

		// Ambil file lama dari database
		$query = "SELECT file_nie FROM tb_kat_produk WHERE id_kat_produk = '$id_kat_produk'";
		$result = mysqli_query($connect, $query);
		$row = mysqli_fetch_assoc($result);
		$file_lama = $row['file_nie'] ?? '';

		$file_path_db = $file_lama; // Default: tetap pakai file lama

		// **Cek apakah pengguna mengunggah file baru**
		if (!empty($_FILES["fileku"]["tmp_name"])) {
			$allowed_pdfs = ['application/pdf'];
			$allowed_images = ['image/png', 'image/jpg', 'image/jpeg'];
			$file_type = $_FILES['fileku']['type'];

			$new_file_name = str_replace(' ', '_', $nama_kategori) . '_' . time() . uniqid() . '.pdf';
			$file_path = $upload_dir . $new_file_name;
			$file_path_db = 'files/' . $new_file_name;

			if (!is_dir($upload_dir)) {
				mkdir($upload_dir, 0777, true);
			}

			// **Hapus file lama jika ada**
			if (!empty($file_lama) && file_exists(__DIR__ . '/../' . $file_lama)) {
				unlink(__DIR__ . '/../' . $file_lama);
			}

			if (in_array($file_type, $allowed_pdfs)) {
				if (!move_uploaded_file($_FILES['fileku']['tmp_name'], $file_path)) {
					throw new Exception("Gagal memindahkan file PDF");
				}
				// Enkripsi file
				file_put_contents($file_path, encryptFile($file_path, $fileKey));
			} elseif (in_array($file_type, $allowed_images)) {
				// Konversi gambar ke PDF
				$pdf = new TCPDF();
				$pdf->AddPage();
				$pdf->Image($_FILES['fileku']['tmp_name'], 10, 10, 190, '', '', '', '', false, 300);
				$pdf->Output($file_path, 'F');

				// Enkripsi file
				file_put_contents($file_path, encryptFile($file_path, $fileKey));
			}
		}

		// **Update database tanpa mengubah file jika tidak ada file baru**
		$stmt = $connect->prepare("UPDATE tb_kat_produk 
			SET nama_kategori = ?, id_merk = ?, no_izin_edar = ?, tgl_terbit = ?, berlaku_sampai = ?, file_nie = ? , updated_by = ?
			WHERE id_kat_produk = ?");
		$stmt->bind_param("ssssssss", $nama_kategori, $merk, $nie, $tgl_terbit, $expired_date, $file_path_db, $id_user, $id_kat_produk);

		if ($stmt->execute()) {
			$_SESSION['info'] = 'Diupdate';
			header("Location: ../kategori-produk.php");
			exit;
		} else {
			$_SESSION['info'] = 'Data Gagal Diupdate';
			exit;
		}
	// Hapus 
	} elseif ($sanitasi_get['hapus-kat-produk']) {
		//tangkap URL dengan $sanitasi_get
		$idh = decrypt($sanitasi_get['hapus-kat-produk'], $key_global);

		// perintah queery sql untuk hapus data
		$sql = "DELETE FROM tb_kat_produk WHERE id_kat_produk='$idh'";
		$query_del = mysqli_query($connect, $sql) or die(mysqli_error($connect));

		if ($query_del) {
			$_SESSION['info'] = 'Dihapus';
			header("Location:../kategori-produk.php");
		} else {
			$_SESSION['info'] = 'Data Gagal Dihapus';
			header("Location:../kategori-produk.php");
		}
	}
?>